// packages/pena-svelte/src/lib/Pena.svelte
<script lang="ts">
  import Pena from '@privyid/pena'
  import type { PenaOption, Payload } from '@privyid/pena'
  import { createEventDispatcher, onDestroy } from 'svelte'

  export let url: PenaOption['url']
  export let lang: PenaOption['lang'] = undefined
  export let signature: PenaOption['signature'] = undefined
  export let layout: PenaOption['layout'] = undefined
  export let privyId: PenaOption['privyId'] = undefined
  export let ratio: PenaOption['ratio'] = undefined
  export let needScrollTo: PenaOption['needScrollTo'] = undefined

  let target: HTMLDivElement
  let cleanup: ReturnType<typeof Pena.openDoc>

  const emit = createEventDispatcher<{ afterAction: Payload }>()

  const onAfterAction = (payload: Payload) => {
    emit('afterAction', payload)
  }

  $: if (target) {
    if (cleanup)
      cleanup()

    cleanup = Pena.openDoc({
      container    : target,
      url          : url,
      lang         : lang,
      signature    : signature,
      layout       : layout,
      privyId      : privyId,
      ratio        : ratio,
      onAfterAction: onAfterAction,
      needScrollTo : needScrollTo,
    })
  }

  onDestroy(() => {
    if (cleanup)
      cleanup()
  })
</script>

<div class="pena__container" bind:this={target}></div>

// packages/pena-angular/projects/lib/src/lib/pena.component.ts
import {
  Component,
  Input,
  Output,
  ViewChild,
  EventEmitter,
} from '@angular/core'
import type { ElementRef } from '@angular/core'
import Pena from '@privyid/pena'
import type { PenaOption, Payload } from '@privyid/pena'

@Component({
  selector: 'pena',
  template: '<div #container class="pena__container"></div>',
  styles  : [],
})
export class PenaComponent {
  cleanUp?: ReturnType<typeof Pena.openDoc>

  @Input('url')
    url!: PenaOption['url']

  @Input('layout')
    layout: PenaOption['layout']

  @Input('lang')
    lang: PenaOption['lang']

  @Input('debug')
    debug: PenaOption['debug']

  @Input('privyId')
    privyId: PenaOption['privyId']

  @Input('visibility')
    visibility: PenaOption['visibility']

  @Input('signature')
    signature: PenaOption['signature']

  @Input('ratio')
    ratio: PenaOption['ratio']

  @Input('needScrollTo')
    needScrollTo: PenaOption['needScrollTo']

  @ViewChild('container')
    container?: ElementRef<HTMLDivElement>

  @Output('afterAction')
    afterAction = new EventEmitter<Payload>()

  // onMounted
  ngAfterViewInit () {
    this.render()
  }

  ngOnChanges () {
    this.render()
  }

  render () {
    if (this.cleanUp)
      this.cleanUp()

    if (this.container?.nativeElement) {
      this.cleanUp = Pena.openDoc({
        container    : this.container.nativeElement,
        url          : this.url,
        layout       : this.layout,
        lang         : this.lang,
        debug        : this.debug,
        privyId      : this.privyId,
        visibility   : this.visibility,
        signature    : this.signature,
        ratio        : this.ratio,
        needScrollTo : this.needScrollTo,
        onAfterAction: this.onAfterAction.bind(this),
      })
    }
  }

  onAfterAction (event: Payload) {
    this.afterAction.emit(event)
  }

  ngOnDestroy () {
    if (this.cleanUp)
      this.cleanUp()
  }
}
