// packages/pena-react/src/Pena.tsx
import {
  useEffect,
  useRef,
} from 'react'
import Pena from '@privyid/pena'
import type { FC } from 'react'
import type { PenaOption } from '@privyid/pena'

const PenaReact: FC<Omit<PenaOption, 'container'>> = (props) => {
  const target = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (target.current) {
      const cleanup = Pena.openDoc({
        container    : target.current,
        url          : props.url,
        lang         : props.lang,
        signature    : props.signature,
        layout       : props.layout,
        privyId      : props.privyId,
        ratio        : props.ratio,
        needScrollTo : props.needScrollTo,
        onAfterAction: props.onAfterAction,
      })

      return cleanup
    }
  }, [props])

  return (
    <div
      ref={target}
      className="pena__container" />
  )
}

export default PenaReact

// packages/pena-svelte/src/lib/Pena.svelte
<script lang="ts">
  import Pena from '@privyid/pena'
  import type { PenaOption, Payload } from '@privyid/pena'
  import { createEventDispatcher, onDestroy } from 'svelte'

  export let url: PenaOption['url']
  export let lang: PenaOption['lang'] = undefined
  export let signature: PenaOption['signature'] = undefined
  export let layout: PenaOption['layout'] = undefined
  export let privyId: PenaOption['privyId'] = undefined
  export let ratio: PenaOption['ratio'] = undefined
  export let needScrollTo: PenaOption['needScrollTo'] = undefined

  let target: HTMLDivElement
  let cleanup: ReturnType<typeof Pena.openDoc>

  const emit = createEventDispatcher<{ afterAction: Payload }>()

  const onAfterAction = (payload: Payload) => {
    emit('afterAction', payload)
  }

  $: if (target) {
    if (cleanup)
      cleanup()

    cleanup = Pena.openDoc({
      container    : target,
      url          : url,
      lang         : lang,
      signature    : signature,
      layout       : layout,
      privyId      : privyId,
      ratio        : ratio,
      onAfterAction: onAfterAction,
      needScrollTo : needScrollTo,
    })
  }

  onDestroy(() => {
    if (cleanup)
      cleanup()
  })
</script>

<div class="pena__container" bind:this={target}></div>
