// packages/pena-react/dev/App.tsx
import React, { useState } from 'react'
import PenaReact, { type Payload } from '..'

function App () {
  const url                       = new URL('dev/testpage.html', location.origin).href
  const [layoutFit, setLayoutFit] = useState(false)

  function changeLayout () {
    setLayoutFit((value) => !value)
  }

  function onAfterAction (event: Payload) {
    // eslint-disable-next-line no-console
    console.log(event.action, event.data)
  }

  return (
    <div style={{ display: 'flex' }}>
      <div style={{ width: '50%' }}>
        <PenaReact
          url={url}
          layout={layoutFit ? 'fit' : 'fixed'}
          onAfterAction={onAfterAction} />
      </div>
      <div style={{ width: '50%' }}>
        <button onClick={changeLayout}>Change Layout</button>
      </div>
    </div>
  )
}

export default App

// packages/pena-angular/projects/dev/src/app/app.component.ts
import { Component } from '@angular/core'
import type { Payload, Placement } from '@privyid/pena'

@Component({
  selector   : 'app-root',
  templateUrl: './app.component.html',
  styleUrls  : ['./app.component.css'],
})
export class AppComponent {
  title = 'dev'

  layoutFit = false

  signature: Placement = {
    x   : 50,
    y   : 30,
    page: 1,
  }

  changeLayout () {
    this.layoutFit = !this.layoutFit
  }

  onAfterAction (event: Payload) {
    // eslint-disable-next-line no-console
    console.log(event.action, event.data)
  }
}

<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content below * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * Delete the template below * * * * * * * * * * -->
<!-- * * * * * * * to get started with your project! * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->

<pena
  url="https://reactnative.dev/"
  layout="fit"
  [signature]="signature"
/>

<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content above * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * End of Placeholder * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->

<router-outlet></router-outlet>
