// packages/pena-svelte/src/Pena.svelte
<script lang="ts">
  import Pena from '@privyid/pena'
  import { createEventDispatcher, onDestroy } from 'svelte'

  export let url: Pena.PenaOption['url']
  export let lang: Pena.PenaOption['lang'] = undefined
  export let signature: Pena.PenaOption['signature'] = undefined
  export let layout: Pena.PenaOption['layout'] = undefined
  export let privyId: Pena.PenaOption['privyId'] = undefined

  let target: HTMLDivElement
  let cleanup: ReturnType<typeof Pena.docSign>

  const emit = createEventDispatcher<{ afterAction: Pena.Payload }>()

  const onAfterAction: Pena.PenaOption['onAfterAction'] = (payload) => {
    emit('afterAction', payload)
  }

  $: if (target) {
    if (cleanup)
      cleanup()

    cleanup = Pena.docSign({
      container    : target,
      url          : url,
      lang         : lang,
      signature    : signature,
      layout       : layout,
      privyId      : privyId,
      onAfterAction: onAfterAction,
    })
  }

  onDestroy(() => {
    if (cleanup)
      cleanup()
  })
</script>

<div class="pena__container" bind:this={target}></div>

// packages/pena-react/src/Pena.tsx
import { FC, useEffect, useRef } from 'react'
import Pena from '@privyid/pena'

const PenaReact: FC<Omit<Pena.PenaOption, 'container'>> = (props) => {
  const target = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (target.current) {
      const cleanup = Pena.docSign({
        container    : target.current,
        url          : props.url,
        lang         : props.lang,
        signature    : props.signature,
        layout       : props.layout,
        privyId      : props.privyId,
        onAfterAction: props.onAfterAction,
      })

      return cleanup
    }
  }, [props])

  return (
    <div
      ref={target}
      className="pena__container" />
  )
}

export default PenaReact
